spring:
  datasource:
    url: jdbc:mysql://192.168.137.200:3306/db_test
    username: root
    password: root123456

mybatis:
  type-aliases-package: com.example.springboot.entity
  mapper-locations: classpath:mapper/*.xml